services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: packster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scheme.sql:/docker-entrypoint-initdb.d/scheme.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d packster"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
